# Copyright (c) MAPFRE DevOps Platform
#
# Pull Request Workflow. Triggers when:
#   - A pull request from feature to develop is created / synchronized
#   - A pull request from hotfix to main is created / synchronized
#
# Required secrets:
#   - AZURE_ARTIFACTS_PW      (Organization)
#   - MAR2_GITHUB_GIT_TOKEN   (Repository) This token is used to commit and push changes to the repository. It is neccessary permissions to do it, 
#                             so it is recommended to use a personal access token with the necessary permissions, tipically owner permissions.
#   - SONAR_TOKEN             (Repository) Secret with the SonarQube token

name: PR workflow
run-name: "Build and Test #${{ github.run_number }}: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
      - main
      - 'release/**'

env:
  

  # Environment - For CDK Synth
  # Source branch hotfix -> pre
  # Source branch feature -> dev
  ENV: ${{ (contains(github.event.pull_request.head.ref, 'hotfix/') || contains(github.event.pull_request.head.ref, 'develop')) && 'pre' || 'dev' }}

jobs:
  pull-request:
    name: Build and Test
    if: ( contains(github.event.pull_request.head.ref, 'feature/') || contains(github.event.pull_request.head.ref, 'hotfix/') || contains(github.event.pull_request.head.ref, 'develop') )
    # Self-hosted Runner
    # hotfix -> pre (AWS account)
    # feature -> dev (AWS account)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print environment
        run: echo "ENV is $ENV"  
    
